//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPlanningMonitorng
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        public Barang()
        {
            this.Detail_penjualan = new HashSet<Detail_penjualan>();
            this.Penjualans = new HashSet<Penjualan>();
            this.Rencanas = new HashSet<Rencana>();
            this.Stoks = new HashSet<Stok>();
        }
    
        public int id_barang { get; set; }
        public string nama_barang { get; set; }
        public decimal harga { get; set; }
        public string kategori { get; set; }
    
        public virtual ICollection<Detail_penjualan> Detail_penjualan { get; set; }
        public virtual ICollection<Penjualan> Penjualans { get; set; }
        public virtual ICollection<Rencana> Rencanas { get; set; }
        public virtual ICollection<Stok> Stoks { get; set; }
    }
}
