//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPlanningMonitorng
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karyawan
    {
        public Karyawan()
        {
            this.Penjualans = new HashSet<Penjualan>();
            this.Kelompoks = new HashSet<Kelompok>();
        }
    
        public int id_karyawan { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string no_telp { get; set; }
        public System.DateTime tanggal_lahir { get; set; }
        public string photo { get; set; }
    
        public virtual ICollection<Penjualan> Penjualans { get; set; }
        public virtual ICollection<Kelompok> Kelompoks { get; set; }
    }
}
