//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPlanningMonitorng
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penjualan
    {
        public Penjualan()
        {
            this.Detail_penjualan = new HashSet<Detail_penjualan>();
        }
    
        public int id_penjualan { get; set; }
        public Nullable<int> id_barang { get; set; }
        public Nullable<int> id_toko { get; set; }
        public Nullable<int> id_karyawan { get; set; }
        public System.DateTime tanggal_transaksi { get; set; }
        public double jumlah_total { get; set; }
    
        public virtual Barang Barang { get; set; }
        public virtual ICollection<Detail_penjualan> Detail_penjualan { get; set; }
        public virtual Karyawan Karyawan { get; set; }
        public virtual Toko Toko { get; set; }
    }
}
