//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPlanningMonitorng
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rencana
    {
        public int id_target { get; set; }
        public Nullable<int> id_barang { get; set; }
        public int target_jual { get; set; }
    
        public virtual Barang Barang { get; set; }
    }
}
