//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPlanningMonitorng
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class psbkEntities2 : DbContext
    {
        public psbkEntities2()
            : base("name=psbkEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barang> Barangs { get; set; }
        public virtual DbSet<Detail_penjualan> Detail_penjualan { get; set; }
        public virtual DbSet<Karyawan> Karyawans { get; set; }
        public virtual DbSet<Kelompok> Kelompoks { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Penjualan> Penjualans { get; set; }
        public virtual DbSet<Rencana> Rencanas { get; set; }
        public virtual DbSet<Stok> Stoks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Toko> Tokoes { get; set; }
    }
}
