//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPlanningMonitorng
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toko
    {
        public Toko()
        {
            this.Penjualans = new HashSet<Penjualan>();
            this.Stoks = new HashSet<Stok>();
        }
    
        public int id_toko { get; set; }
        public string nama_toko { get; set; }
        public string alamat { get; set; }
        public string wilayah { get; set; }
    
        public virtual ICollection<Penjualan> Penjualans { get; set; }
        public virtual ICollection<Stok> Stoks { get; set; }
    }
}
